# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: pod-gateway-config
#   namespace: vpn-gateway
#   labels:
#     kasten.io/backup-volume: "enabled"
# spec:
#   accessModes:
#     - ReadWriteOnce
#   resources:
#     requests:
#       storage: 100Mi
#   storageClassName: hdd-nfs-storage
