---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - goldilocks
  # - grafana
  - kube-prometheus-stack
  # - loki
  # - promtail
  # - speedtest-exporter
  # - thanos
  # - uptimerobot-heartbeat
  # - vpa
