---
# yamllint disable rule:line-length
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: goldilocks
  namespace: monitoring
spec:
  interval: 15m
  chart:
    spec:
      chart: goldilocks
      version: 6.2.0
      sourceRef:
        kind: HelmRepository
        name: fairwinds
        namespace: flux-system
      interval: 15m
  timeout: 20m
  values:
    vpa:
      # vpa.enabled -- If true, the vpa will be installed as a sub-chart
      enabled: true
      updater:
        enabled: true
    controller:
      # controller.enabled -- Whether or not to install the controller deployment
      enabled: true
      rbac:
        # controller.rbac.create -- If set to true, rbac resources will be created for the controller
        create: true
        # controller.rbac.enableArgoproj -- If set to true, the clusterrole will give access to argoproj.io resources
        enableArgoproj: true
        # controller.rbac.extraRules -- Extra rbac rules for the controller clusterrole
        extraRules: []
      serviceAccount:
        # controller.serviceAccount.create -- If true, a service account will be created for the controller. If set to false, you must set `controller.serviceAccount.name`
        create: true
        # controller.serviceAccount.name -- The name of an existing service account to use for the controller. Combined with `controller.serviceAccount.create`
        name: "goldilocksSA"
      resources:
        requests:
          cpu: 15m
          memory: 145M
        limits:
          memory: 174M
    dashboard:
      replicaCount: 1
      ingress:
        enabled: true
        ingressClassName: "nginx"
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-production"
          external-dns.alpha.kubernetes.io/target: "ipv4.${SECRET_DOMAIN}"
          external-dns/is-public: "true"
          hajimari.io/enable: "true"
          hajimari.io/icon: "sun-compass"
        hosts:
          - host: &host "goldilocks.${SECRET_DOMAIN}"
            paths:
              - path: /
                type: Prefix
        tls:
          - hosts:
              - *host
            secretName: "goldilocks-tls"
      # resources:
      #   requests:
      #     cpu: 15m
      #     memory: 64M
      #   limits:
      #     memory: 64M
