---
apiVersion: v1
kind: Secret
metadata:
  name: discord-url
  namespace: flux-system
stringData:
  address: ${SECRET_FLUX_DISCORD_ADDRESS}
---
apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Provider
metadata:
  name: discord
  namespace: flux-system
spec:
  type: discord
  username: Flux
  channel: flux
  secretRef:
    name: discord-url
---
# ? Notify on  Helm/Git repo changes - everything
apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Alert
metadata:
  name: on-call-webapp
  namespace: flux-system
spec:
  providerRef:
    name: discord
  eventSeverity: info
  eventSources:
    - kind: GitRepository
      name: "*"
    - kind: HelmRelease
      name: "*"
  suspend: false
---
# ? Notify on Kustomization - error only
apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Alert
metadata:
  name: on-error-webapp
  namespace: flux-system
spec:
  providerRef:
    name: discord
  eventSeverity: error
  eventSources:
    - kind: Kustomization
      name: "*"
  suspend: false
