# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: pvc-codeserver
#   namespace: development
# spec:
#   storageClassName: hdd-nfs-storage
#   accessModes:
#     - ReadWriteMany
#   resources:
#     requests:
#       storage: 500Mi
# #  volumeName: clarice

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: code-server-pvc
  namespace: development
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: hdd-nfs-storage
