---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: code-server
  namespace: development
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://wrmilling.github.io/wrmilling-charts/
      chart: code-server
      version: 2.5.0
      sourceRef:
        kind: HelmRepository
        name: wrmilling-charts
        namespace: flux-system
      interval: 5m
  values:
    env:
      PASSWORD: ${SECRET_CODE_SERVER_PW}
    ingress:
      enabled: true
      annotations:
        external-dns.alpha.kubernetes.io/target: "ipv4.${SECRET_DOMAIN}"
        external-dns/is-public: "true"
        hajimari.io/enable: "true"
        hajimari.io/icon: "vs-code"
        cert-manager.io/cluster-issuer: "letsencrypt-production"
        nginx.ingress.kubernetes.io/auth-url: "https://oauth.${SECRET_DOMAIN}/oauth2/auth"
        nginx.ingress.kubernetes.io/auth-signin: "https://oauth.${SECRET_DOMAIN}/oauth2/start?rd=$scheme://$best_http_host$request_uri"
        nginx.ingress.kubernetes.io/auth-response-headers: "x-auth-request-user, x-auth-request-email, x-auth-request-access-token"
      hosts:
        - host: code.${SECRET_DOMAIN}
          paths:
            - /
      ingressClassName: "nginx"
      tls:
        - secretName: code-tls
          hosts:
            - code.${SECRET_DOMAIN}
    persistence:
      enabled: true
      existingClaim: code-server-pvc
    podAnnotations:
      backup.velero.io/backup-volumes: data
