---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hdd-nfs-pvc-1
  namespace: storage
spec:
  storageClassName: hdd-nfs-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Mi
