apiVersion: v1
kind: Secret
type: kubernetes.io/basic-auth
metadata:
    name: postgres-superuser
    namespace: default
stringData:
    username: ${SECRET_POSTGRESSQL_USER}
    password: ${SECRET_POSTGRESSQL_PASSWORD}
---
kind: Secret
apiVersion: v1
type: Opaque
metadata:
    name: postgres-minio
    namespace: default
    labels:
        k8s.enterprisedb.io/reload: "true"
stringData:
    MINIO_ACCESS_KEY: ${SECRET_MINIO_ROOT_USER}
    MINIO_SECRET_KEY: ${SECRET_MINIO_ROOT_PASSWORD}
