---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cert-manager
  - system-upgrade-controller
  - external-snapshotter
  - kyverno
  - kube-prometheus-stack
  - cloudnative-pg
  - velero
