---
# yamllint disable rule:line-length
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: qbittorrent-vpn
  namespace: downloads
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: qbittorrent
      version: 13.5.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
      interval: 5m
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    # * needed for an static IP
    hostname: torrent
    image:
      repository: ghcr.io/k8s-at-home/qbittorrent
      tag: latest
    updateStrategy: Recreate
    env:
      TZ: "${TZ}"
    settings:
      automaticPortSetup: true
    service:
      main:
        ports:
          http:
            port: 80
            targetPort: 8080
      bittorrent:
        enabled: true
    ingress:
      main:
        enabled: true
        ingressClassName: "nginx"
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-production"
          external-dns.alpha.kubernetes.io/target: "ipv4.${SECRET_DOMAIN}"
          external-dns/is-public: "true"
          hajimari.io/enable: "true"
          hajimari.io/icon: "cloud-download-outline"
        hosts:
          - host: "qb-vpn.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - "qb-vpn.${SECRET_DOMAIN}"
            secretName: "qb-vpn-tls"
    podSecurityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
      fsGroupChangePolicy: "OnRootMismatch"
    persistence:
      config:
        enabled: true
        existingClaim: qbittorrent-vpn-config
      media:
        enabled: true
        type: custom
        volumeSpec:
          nfs:
            server: "${NAS_SERVER}"
            path: "${NAS_PATH_MEDIA}"
        mountPath: /media
    podAnnotations:
      backup.velero.io/backup-volumes: config
      setGateway: "true"
      configmap.reloader.stakater.com/reload:
        ["qbittorrent-vpn-scripts", "vpn-gateway-pod-gateway"]
    resources:
      requests:
        memory: 250Mi
        cpu: 500m
      limits:
        memory: 2000Mi
