---
kind: Secret
apiVersion: v1
type: Opaque
metadata:
    name: emqx-config
    namespace: default
stringData:
    admin_password: ${SECRET_EMQX_ADMIN_PASSWORD}
    user_1_username: ${SECRET_EMQX_USER1_NAME}
    user_1_password: ${SECRET_EMQX_USER1_PASSWORD}
