apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    kasten.io/backup-volume: enabled
  name: qbittorrent-config
  namespace: downloads
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: hdd-nfs-storage
