---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: minio-nfs
spec:
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteMany
  storageClassName: hdd-nfs-storage
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: "${NAS_SERVER}"
    path: "${NAS_PATH_MINIO}"
  # TODO: cleanup
  # mountOptions:
  #   - nfsvers=4.2
  #   - nconnect=8
  #   - hard
  #   - noatime
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-nfs
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: hdd-nfs-storage
  resources:
    requests:
      storage: 1Mi
