---
# yamllint disable rule:line-length
# ? icons from : https://materialdesignicons.com/
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: hajimari
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://hajimari.io
      chart: hajimari
      version: 1.2.0
      sourceRef:
        kind: HelmRepository
        name: hajimari
        namespace: flux-system
      interval: 5m
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    env:
      TZ: "${TZ}"
    image:
      repository: ghcr.io/toboshii/hajimari
      tag: v0.2.0
    hajimari:
      defaultEnable: false
      namespaceSelector:
        matchNames:
          - default
          - networking
          - media
          - tools
          - monitoring
          - storage
          - downloads
          - security
          - development
      name: "Fabrice"
      customApps:
        - name: Plex [local]
          url: "http://${SVC_PLEX_ADDR}:32400"
          icon: plex
        - name: NAS [local]
          url: http://192.168.1.3
          icon: nas
        - name: Home-Assistant [local]
          url: "http://${SVC_HOME_ASSISTANT_ADDR}:8123"
          icon: home-assistant
        - name: EMQX [local]
          url: "http://${SVC_EMQX_ADDR}:18083"
          icon: table-network
      groups:
        - name: Communicate
          links:
            - name: Discord
              url: "https://discord.com"
            - name: Gmail
              url: "https://gmail.com"
            - name: Slack
              url: "https://slack.com/signin"
        - name: Cloud
          links:
            # - name: Box
            #   url: "https://box.com"
            - name: Dropbox
              url: "https://dropbox.com"
            - name: Drive
              url: "https://drive.google.com"
        # - name: Design
        #   links:
        #     - name: Awwwards
        #       url: "https://awwwards.com"
        #     - name: Dribbble
        #       url: "https://dribbble.com"
        #     - name: Muz.li
        #       url: "https://medium.muz.li/"
        - name: Dev
          links:
            - name: Codepen
              url: "https://codepen.io/"
            - name: Devdocs
              url: "https://devdocs.io"
            - name: Devhints
              url: "https://devhints.io"
        - name: Lifestyle
          links:
            - name: Design Milk
              url: "https://design-milk.com/category/interior-design/"
            - name: Dwell
              url: "https://www.dwell.com/"
            - name: Freshome
              url: "https://www.mymove.com/freshome/"
        - name: Media
          links:
            # - name: Spotify
            #   url: "http://browse.spotify.com"
            - name: Trakt
              url: "http://trakt.tv"
            - name: YouTube
              url: "https://youtube.com/feed/subscriptions"
        - name: Reading
          links:
            - name: Instapaper
              url: "https://www.instapaper.com/u"
            - name: Medium
              url: "http://medium.com"
            - name: Reddit
              url: "http://reddit.com"
        - name: Tech
          links:
            - name: Hacker News
              url: "https://news.ycombinator.com/"
            - name: The Verge
              url: "https://theverge.com/"
            - name: MIT Technology Review
              url: "https://www.technologyreview.com/"
    ingress:
      main:
        enabled: true
        ingressClassName: "nginx"
        annotations:
          hajimari.io/enable: "true"
          hajimari.io/icon: "weather-sunset"
          cert-manager.io/cluster-issuer: "letsencrypt-production"
          external-dns.alpha.kubernetes.io/target: "ipv4.${SECRET_DOMAIN}"
          external-dns/is-public: "true"
          nginx.ingress.kubernetes.io/auth-url: "https://oauth.${SECRET_DOMAIN}/oauth2/auth"
          nginx.ingress.kubernetes.io/auth-signin: "https://oauth.${SECRET_DOMAIN}/oauth2/start?rd=$scheme://$best_http_host$request_uri"
          nginx.ingress.kubernetes.io/auth-response-headers: "x-auth-request-user, x-auth-request-email, x-auth-request-access-token"
        hosts:
          - host: "hajimari.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - "hajimari.${SECRET_DOMAIN}"
            secretName: "hajimari-tls"
    persistence:
      data:
        enabled: true
        existingClaim: hajimari-config
    podAnnotations:
      configmap.reloader.stakater.com/reload: "hajimari-settings"
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        memory: 256Mi
